from faker import Faker
import random
from csv_helper import *

fake = Faker('id_ID')

def generate_dummy_user(n):
    """
    A function for generating user data.
    name and phone number of the user is generated by Faker.
    
    Args
    n (int) : desired number of users to be generated

    Return
    user_data (list)
    """
    city_ids = [
        3171,
        3172,
        3173,
        3174,
        3175,
        3573,
        3578,
        3471,
        3273,
        1371,
        1375,
        6471,
        6472,
        7371,
        5171,
    ]
    user_data = []

    for i in range(1,n+1):
        user_data.append({
            "user_id": i,
            "name": fake.name(),
            "phone_number": fake.phone_number(),
            "city_id": random.choice(city_ids),
            "role" :random.choice(["Buyer", "Seller"])
        })
    
    return user_data

#define column for user table
user_cols = ['user_id', 'name', 'phone_number', 'city_id', 'role']
#generate rows for user table
user_rows = generate_dummy_user(100)

#save to user.csv
save_to_csv('csv/users.csv', user_cols, user_rows)